package com.lenovo.lps.sus;
/* loaded from: classes.dex */
public enum EventType {
    SUS_FAIL_NETWORKUNAVAILABLE,
    SUS_FAIL_NOWLANCONNECTED,
    SUS_FAIL_INSUFFICIENTSTORAGESPACE,
    SUS_FAIL_DOWNOLADFOLDER_FOLDER_NOTEXIST,
    SUS_FAIL_DOWNLOAD_EXCEPTION,
    SUS_WARNING_PENDING,
    SUS_DOWNLOADSTART,
    SUS_DOWNLOADCOMPLETE,
    SUS_QUERY_RESP,
    SUS_TESTSERVER_RESP
}
